/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package oasis;

/**
 *
 * @author Spencer Dale Colton
 */
public class OasisLauncher extends javax.swing.JFrame {

    /**
     * Creates new form OasisLauncher
     */
    public OasisLauncher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serversDialog = new javax.swing.JDialog();
        noServers = new java.awt.Label();
        serversOK = new java.awt.Button();
        oasisLogo = new javax.swing.JLabel();
        gameDescriptionScrollPane = new javax.swing.JScrollPane();
        gameDescription = new javax.swing.JTextArea();
        usernameVar = new java.awt.TextField();
        passwordVar = new java.awt.TextField();
        loginButton = new java.awt.Button();
        saveUsername = new java.awt.Checkbox();
        savePassword = new java.awt.Checkbox();
        copyrightFooter = new java.awt.Label();
        updateNews = new java.awt.Button();

        serversDialog.setModal(true);
        serversDialog.setUndecorated(true);

        noServers.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        noServers.setName(""); // NOI18N
        noServers.setText("Sorry, we have no servers available to process your request.");

        serversOK.setLabel("OK");
        serversOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serversOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout serversDialogLayout = new javax.swing.GroupLayout(serversDialog.getContentPane());
        serversDialog.getContentPane().setLayout(serversDialogLayout);
        serversDialogLayout.setHorizontalGroup(
            serversDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serversDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noServers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(serversDialogLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(serversOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        serversDialogLayout.setVerticalGroup(
            serversDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serversDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noServers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serversOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OASIS Launcher");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        oasisLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oasis/OASIS Logo.png"))); // NOI18N

        gameDescription.setEditable(false);
        gameDescription.setBackground(new java.awt.Color(240, 240, 240));
        gameDescription.setColumns(13);
        gameDescription.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        gameDescription.setLineWrap(true);
        gameDescription.setRows(5);
        gameDescription.setText("Welcome to OASIS! OASIS is reality, without the reality! Anything can happen that can happen in reality, and then some! Property can be sold, businesses can be started, and a family can be raised, all within software! ");
        gameDescription.setWrapStyleWord(true);
        gameDescriptionScrollPane.setViewportView(gameDescription);

        passwordVar.setEchoChar('*');
        passwordVar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordVarKeyPressed(evt);
            }
        });

        loginButton.setLabel("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        saveUsername.setLabel("Save Username");

        savePassword.setLabel("Save Password");
        savePassword.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                savePasswordItemStateChanged(evt);
            }
        });

        copyrightFooter.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        copyrightFooter.setText("Copyright © 2013 [company name]             All Rights Reserved");

        updateNews.setLabel("Update News");
        updateNews.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateNewsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(oasisLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(updateNews, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameVar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordVar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(saveUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(savePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(loginButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(copyrightFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 302, Short.MAX_VALUE)
                    .addComponent(gameDescriptionScrollPane, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(oasisLogo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gameDescriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(savePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateNews, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(copyrightFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setIconImage(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("oasis/OASIS Logo Sun.png")).getImage());
        setLocationRelativeTo(null);
        saveUsername.setFocusable(false);
        savePassword.setFocusable(false);
        saveUsername.setState(true);
        serversDialog.setLocationRelativeTo(this);
    }//GEN-LAST:event_formWindowOpened

    private void savePasswordItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_savePasswordItemStateChanged
        if(savePassword.getState()){
            saveUsername.setState(true);
        }
    }//GEN-LAST:event_savePasswordItemStateChanged

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        login();
    }//GEN-LAST:event_loginButtonActionPerformed

    private void passwordVarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordVarKeyPressed
        if(evt.getKeyCode() == 10){
            login();
        }
    }//GEN-LAST:event_passwordVarKeyPressed

    private void updateNewsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateNewsActionPerformed
        
    }//GEN-LAST:event_updateNewsActionPerformed

    private void serversOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serversOKActionPerformed
        serversDialog.setVisible(false);
    }//GEN-LAST:event_serversOKActionPerformed

    private void login(){
        String username;
        username = usernameVar.getText();
        String password;
        password = passwordVar.getText();
        if("pavilion99".equals(username) && "Spencer3899$".equals(password)){
            
        }else{
            serversDialog.setVisible(true);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OasisLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OasisLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OasisLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OasisLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OasisLauncher().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label copyrightFooter;
    private javax.swing.JTextArea gameDescription;
    private javax.swing.JScrollPane gameDescriptionScrollPane;
    private java.awt.Button loginButton;
    private java.awt.Label noServers;
    private javax.swing.JLabel oasisLogo;
    private java.awt.TextField passwordVar;
    private java.awt.Checkbox savePassword;
    private java.awt.Checkbox saveUsername;
    private javax.swing.JDialog serversDialog;
    private java.awt.Button serversOK;
    private java.awt.Button updateNews;
    private java.awt.TextField usernameVar;
    // End of variables declaration//GEN-END:variables
}
